import React from "react";
import Helmet from "react-helmet";

const TermsAndConditions = () => {
  const TermsAndConditionsContent = [
    {
      heading: "",
      content: [
        {
          subheading: "",
          content:
            "Welcome to Headgen.ai, a service provided by Playcloud Technologies Private Limited. By using our website and services, you agree to comply with and be bound by the following Terms of Service. Please read these terms carefully.",
        },
      ],
    },
    {
      heading: "Service Description",
      content: [
        {
          subheading: "",
          content:
            "Headgen.ai offers users the ability to upload a single selfie and receive 8 professional headshot images suitable for LinkedIn or corporate use.",
        },
      ],
    },

    {
      heading: "Pricing and Payments",
      content: [
        {
          subheading: "",
          content:
            "The service is priced at €9 US Dollars for individuals and €9 US Dollars for team headshots. Payments are securely processed through our payment partner, Stripe. We do not store any payment information on our platform.",
        },
      ],
    },

    {
      heading: "Image Handling",
      content: [
        {
          subheading: "",
          content:
            "Once the image is submitted for headshot generation, we do not store the customer’s image or any other personal data.",
        },
      ],
    },

    {
      heading: "Refund Policy",
      content: [
        {
          subheading: "",
          content: (
            <>
              We do not provide automatic refunds for our services. <br />
              If customers encounter issues or are dissatisfied with the
              generated headshot images, they can contact us at
              support@headgen.ai within 7 days of receiving the images. <br />
              Customers should provide detailed information about the issue
              along with relevant screenshots.
              <br />
              Refunds will be considered on a case-by-case basis. If the issue
              is deemed valid, we may offer a refund or other appropriate
              resolution.
            </>
          ),
        },
      ],
    },

    {
      heading: "Customer Support",
      content: [
        {
          subheading: "",
          content: (
            <>
              For any inquiries, concerns, or support, customers can reach our
              Customer Care Number at 9987357345 or contact us via email at
              support@headgen.ai.
            </>
          ),
        },
      ],
    },

    {
      heading: "Intellectual Property",
      content: [
        {
          subheading: "",
          content:
            "The headshot images generated by our service are the intellectual property of the customer. However, customers grant us a license to use these images for the sole purpose of providing the service.",
        },
      ],
    },

    {
      heading: "User Responsibilities",
      content: [
        {
          subheading: "",
          content:
            "Users are responsible for providing accurate and current information during the submission process. Users should comply with all applicable laws and regulations while using our services.",
        },
      ],
    },

    {
      heading: "Modification of Terms",
      content: [
        {
          subheading: "",
          content: (
            <>
              We reserve the right to update and modify these Terms of Service
              at any time. Changes will be effective immediately and will be
              reflected on our website. <br />
              By using Headgen.ai, you acknowledge that you have read and
              understood these Terms of Service. If you do not agree with our
              terms, please refrain from using our services.
            </>
          ),
        },
      ],
    },
  ];

  return (
    <>
    <Helmet>
        <title>
        Terms and Conditions | HeadGen AI - AI Photo Generator & AI Headshot Generator Services
        </title>
        {/* <meta
          name="description"
          content="Discover how HeadGen AI’s AI image generator creates professional, realistic headshots for resumes, teams, doctors, and LinkedIn. Using our AI photo generator, we deliver the best AI Generated images with ease."
        /> */}
      </Helmet>
    <div className="w-full text-white py-24 px-10 xl:px-[250px] bg-[#161616] flex flex-col gap-6 xl:gap-[3.5rem] tracking-wider">
      <h1 className="w-full text-center font-medium text-[44px] md:text-[52px] xl:text-[60px]">
        Terms & Conditions
      </h1>
      <div className="flex flex-col justify-between gap-6 text-[14px] md:text-[16px]  xl:text-[22px] text-[#e4e2e2] font-light h-full">
        {TermsAndConditionsContent &&
          TermsAndConditionsContent?.map((data, idx) => (
            <div className="flex flex-col gap-6">
              <h2 className="font-semibold">
                {data?.heading?.length > 0 && `${idx}. ${data?.heading}`}
              </h2>
              {data?.content &&
                data?.content?.map((subData, idx2) => (
                  <div className="flex flex-col gap-6">
                    {subData?.subheading?.length > 0 && (
                      <h3>
                        {idx}.{idx2} {subData?.subheading}
                      </h3>
                    )}
                    <div>{subData?.content}</div>
                  </div>
                ))}
            </div>
          ))}
      </div>
    </div>
    </>
  );
};

export default TermsAndConditions;
